# Задание 26.
G = 3(A - B)^T * (2C - D), где 
A = [[-2, 3, -4],
    [-3, 5, -2]], 
     
B = [[0, -3, -1],
    [2, 0, -4]], 
     
C = [[0, 4, 1, -3],
    [2, 1, -1, 5]], 
     
D = [[3, 0, 2, -2],
    [0, 3, -3, 0]]

In [11]:
import numpy as np

A = np.array([[-2, 3, -4],
              [-3, 5, -2]])

B = np.array([[0, -3, -1],
              [2, 0, -4]])

C = np.array([[0, 4, 1, -3],
              [2, 1, -1, 5]])

D = np.array([[3, 0, 2, -2],
              [0, 3, -3, 0]])

print(f"A + B = \n{A + B}\n")  # Сложение матриц

print(f"3(A + B) = \n{3 * (A + B)}\n")  # Умножение матрицы на скалярное значение

print(f"3(A + B)^T = \n{3 * (A + B).transpose()}\n")  # Транспонирование и вычитание матриц

print(f"2C - D =\n {2 * C - D}\n")

print(f"G = 3(A - B)^T * (2C - D) =\n {np.dot(3 * (A + B).transpose(), (2 * C - D))}")  # умножение матриц

# 1) Для умножения матриц необходимо обеспечить согласованность: 
# Матрицы А размерности M(строк) x N(столбцов) может умножаться на матрицу размерности N(строк) x P(столбцов
# 
# 2) A * B != B * A (Не коммутативно)
# 
# 3) Пример умножения матриц:
# 
# X = | 100  200  150 |
#     | 50   300  120 |
#     | 80   180  220 |
# 
# Y = | 2.5 |
#     | 3.0 |
#     | 2.2 |
# 
# Z = | 100*2.5 + 200*3.0 + 150*2.2|
#     | 50*2.5 + 300*3.0 + 120*2.2 |
#     | 80*2.5 + 180*3.0 + 220*2.2 |


A + B = 
[[-2  0 -5]
 [-1  5 -6]]

3(A + B) = 
[[ -6   0 -15]
 [ -3  15 -18]]

3(A + B)^T = 
[[ -6  -3]
 [  0  15]
 [-15 -18]]

2C - D =
 [[-3  8  0 -4]
 [ 4 -1  1 10]]

G = 3(A - B)^T * (2C - D) =
 [[   6  -45   -3   -6]
 [  60  -15   15  150]
 [ -27 -102  -18 -120]]


# Задание 32.
Вычислить значение многочлена f(x) от матрицы А.
f(x) = x^3 - x^2 - 1, где
A = [[-2 1],
     [1 0]]

In [13]:
import numpy as np
from numpy import linalg as ln


def f(x):
    return ln.matrix_power(x, 3) - ln.matrix_power(x, 2) - 1


A = np.array([[-2, 1], [1, 0]])
print(f(A))

# Модуль linalg из библиотеки num py, который позволяет осуществлять операции из линейной алгебры для матриц. 

# Пример возведения в степень матрицы:
# | 1  2 | * | 1  2 | = | 1*1 + 2*3  1*2 + 2*4 | = | 7  10 |
# | 3  4 |   | 3  4 |   | 3*1 + 4*3  3*2 + 4*4 |   | 15 22 |
# 
# | 7  10 | * | 1  2 | = | 7*1  + 10*3  7*2 + 10*4  | = | 37  54 |
# | 15 22 |   | 3  4 |   | 15*1 + 22*3  15*2 + 22*4 |   | 81 118 |

[[-18   6]
 [  6  -4]]


# Задание 40
Вычислить определитель
| 2 -3 4 3 |
| 4 -2 3 2 |
| 5 -5 2 3 |
| 3 -4 4 3 |

In [ ]:
import numpy as np
from numpy import linalg as ln

A = np.array([[2, -3, 4, 3], [4, -2, 3, 2], [5, -5, 2, 3], [3, -4, 4, 3]])

Det_A = ln.det(A)

print(Det_A)

# Свойства:
# * |А| == 0 - матрица является сингулярной, и у нее нет обратной матрицы
# * |А| != 0 - матрица называется невырожденной, у нее есть обратная матрица
# * Если матрица умножается на скаляр, то определитель умножается на это число
# * |A^T| = |A|
# * ЕЯСли две строки(или столбца) линейно независимы, то |A| = 0.   (Лин. завис. - одна строка может быть выражена 
# как линейная комбинация другой строки |[[2 3][4 6]]| = 0)

# Если определитель не равен нулю, то система имеет единственное решение, если равен, то система имеет бесконечно много решений или их нет

# В геометрическом смысле определитель указывает насколько матрица изменят объем или площадь. Если он положителен, 
# то матрица сохраняет ориентацию, и объем или площадь увелич., если отриц., матрица изменяет ориент.

# Задание 49
Найти матрицу обратную к данной
А = 
[[6,4,1],
 [5,6,2],
 [1,1,-1]]


In [1]:
import numpy as np
from numpy import linalg as ln

A = np.array([[6, 4, 1], [5, 6, 2], [1, 1, -1]])
A_inv = ln.inv(A)

print(A_inv)

# * Для нахождения обратной матрицы важно убедиться, что она является квадратной
# * Убедиться, что определитель не равне нулю
# 
# Матрица миноров - это матрица, составленная из определителей всех миноров (подматриц),
# полученных из исходной матрицы путем удаления одной или более строк и столбцов.

# Пример:
# A = [[a, b, c],
#      [d, e, f],
#      [g, h, i]]

# M1 = [[e, f], 
#       [h, i]]
# M2 = [[d, f],
#       [g, i]]
# M3 = [[d, e]
#       [g, h]] и тд
# 
# Матрица миноров будет иметь такой вид:
# Minors(A) = [[det(M1), det(M2), det(M3)],
#             [det(M4), det(M5), det(M6)],
#             [det(M7), det(M8), det(M9)]], где det - определитель
# 
# 
# Для нахождения алгебраических дополнений нужно использовать формулу: Aij = (-1)^i+j * Mij, где i - строка, j - столбец
# Далее произвести транспонирование матрицы алгебраических дополнений Adj(A)
# Последним действием будет разделить каждый элемент транспонированной матрицы алг. дополнений на определитель. А^(-1) = (1/det(A))^Adj(A)

[[ 0.38095238 -0.23809524 -0.0952381 ]
 [-0.33333333  0.33333333  0.33333333]
 [ 0.04761905  0.0952381  -0.76190476]]


# Задание 51
Решить матричное уравнение и проверить результат, выполнив умножение матриц исходной задач: AX = B, где
[[-1, -4, 8, 15, -1, 5],
 [-8, 4, -5, 7, -5, 8],
 [7, 3, -14, 7, 8, -2],
 [10, -9, 0, -4, -2, -6],
 [-6, -3, -4, -2, 12, 2],
 [-7, 8, 12, -4, -9, 9]]
             
B = [[3, -5, 9, 3, -1, 0],
     [5, -3, -5, 0, -5, 13],
     [-6, 10, -4, 15, -2, 0],
     [15, -6, 9, -9, -2, -6],
     [8, -3, 5, -5, 8, -1],
     [0, 8, 6, -4, 12, -7]]

In [2]:
import numpy as np
from scipy.linalg import solve

A = np.array([[-1, -4, 8, 15, -1, 5],
             [-8, 4, -5, 7, -5, 8],
             [7, 3, -14, 7, 8, -2],
             [10, -9, 0, -4, -2, -6],
             [-6, -3, -4, -2, 12, 2],
             [-7, 8, 12, -4, -9, 9]])
B = np.array([[3, -5, 9, 3, -1, 0],
              [5, -3, -5, 0, -5, 13],
             [-6, 10, -4, 15, -2, 0],
             [15, -6, 9, -9, -2, -6],
             [8, -3, 5, -5, 8, -1],
             [0, 8, 6, -4, 12, -7]])

X = solve(A, B)

print(X)

# scipy.linalg import solve - решает систему линейных уравнений

[[ 0.76076373  1.05154173  1.27107887  0.23302265  0.89376539 -1.46613399]
 [-2.13269423  1.36624602 -0.93009527  1.39652486  0.18627268 -0.21935091]
 [-0.63217101  0.2252911   0.46509346  0.11585065  0.52686904 -0.76047847]
 [-0.88374555 -0.20010642 -0.49929794  0.85173269 -0.75798208  0.61215765]
 [-0.28605571  0.55021151  0.52985465  0.37968128  0.91898938 -0.81416333]
 [ 2.6514965   0.65320096  2.16985477 -0.90079843  1.74252488 -1.2512476 ]]


# Задание 55
Найти ранг матрицы

In [3]:
import numpy as np
from numpy import linalg as ln

A = np.array([[0,1,-1,3],[2,5,1,11],[1,2,1,4]])

print(ln.matrix_rank(A))

2


# Задание 57
Определить максимальное число линейно независим ы х строк матрицы :


In [4]:
import numpy as np
from numpy import linalg as ln

A = np.array([[1,2,1,4],[0,5,-1,4],[-1,3,4,6]])

print(ln.matrix_rank(A))

3


# Задание 72

In [5]:
import numpy as np

A = np.array([[1, 2, -1],[2,-3,1],[4,1,-1]])
B = np.array([7,3,16])

def solve_slu(A,B):
    Det_A =np.linalg.det(A )
    B1=B.reshape(1,B.shape[0])
    AB =np.vstack((A ,B1))
    if Det_A !=0:
        X =np.linalg.solve(A ,B )
        print('Система имеет единственно решение')
        print(X)
        return
    if Det_A == 0:
        rank_A =np.linalg.matrix_rank(A)
        rank_AB =np.linalg.matrix_rank(AB)
        if rank_A ==rank_AB:
            print('Сиситема имеет бесконечное множество решений, частное решение' + X )
    else: 
        print('Система не имеет решений' )
        return
    
solve_slu(A ,B)
print (np.linalg.matrix_rank(A))
B1=B .reshape(1,B.shape[0])
AB =np.vstack((A ,B1))
print (np.linalg.matrix_rank(AB))
    

2
3
