Задание 92 а)
 Проверить принадлежность данных точек одной прямой: а) А (3; 4; 1), В(1; 0; - 1 ) и С (-2 ;-6 ; -4 );
б) А (3 ; 2; - 1 ), В(5; - 1 ; 4) и С (1 ;-7 ; 12). (Указание: использовать коллинеарность векторов, леж ащ их на одной прямой).

In [1]:
import numpy as np

#              x   y   z
a = np.array([3, 4, 1])
b = np.array([1, 0, -1])
c = np.array([-2, -6, -4])

if b[0] / a[0] == b[1] / a[1] == b[2] / a[2]:
    print('Точки A и B лежат на одной прямой')
    if c[0] / b[0] == c[1] / b[1] == c[2] / b[2]:
        print('Точки B и C лежат на одной прямой')
    else:
        print('Три точки не лежат на одной прямой')
else:
    print('Три точки не лежат на одной прямой')


Три точки не лежат на одной прямой


Задание 92 б)

In [2]:
# задание 92 (б)
import numpy as np

#              x   y   z
a = np.array([3, 2, -1])
b = np.array([5, -1, 4])
c = np.array([1, -7, 12])

if b[0] / a[0] == b[1] / a[1] == b[2] / a[2]:
    print('Точки A и B лежат на одной прямой')
    if c[0] / b[0] == c[1] / b[1] == c[2] / b[2]:
        print('Точки B и C лежат на одной прямой')
    else:
        print('Три точки не лежат на одной прямой')
else:
    print('Три точки не лежат на одной прямой')

Три точки не лежат на одной прямой


задание 93


In [3]:
import numpy as np

a = np.array([-3,  4, -1])
b = np.array([-1,  2,  3])
c = np.array([-4, -2,  1])

x = 4*a + 3*b - 2*c
print(x)

y = -5*a + 4*b + c
print(y)


[-7 26  3]
[  7 -14  18]


задание 94

In [4]:
import numpy as np
import math as m

mod_a = 5
mod_b = 6

# a)
ab_45 = mod_a * mod_b * m.cos(m.pi/4)
print(ab_45)
# б)
ab_60 = mod_a * mod_b * m.cos(m.pi/3)
print(ab_60)
# в)
ab_135 = mod_a * mod_b * m.cos(3*m.pi/4)
print(ab_135)

21.213203435596427
15.000000000000004
-21.213203435596423


Задание 101

In [5]:
import numpy as np

# точки
a = np.array([ 3,  5, -4]) # начало
b = np.array([ 1, -1, -3])
c = np.array([ 7,  2, -6])
d = np.array([-1,  3, -2])

# векторы
ab = b - a
ac = c - a
ad = d - a

matrix = np.vstack([ab, ac, ad])

if np.linalg.det(matrix) == 0:
  print('Векторы лежат в одной плоскости')
else:
   print('Векторы не лежат в одной плоскости')


Векторы лежат в одной плоскости


Задание 104


In [6]:
import numpy as np

a1 = np.array([ 1, -1,  2,  1])
a2 = np.array([ 2,  1, -1,  3])
a3 = np.array([ 6,  0,  2,  8])
a4 = np.array([-1, -2,  3, -2])
a5 = np.array([ 3,  0,  1,  4])

A = np.vstack([a1, a2, a3, a4, a5])

# сингулярное разложение матрицы
u, s, vh = np.linalg.svd(A)

# пороговое значение для определения линейно независмимых векторов
threshold = np.finfo(float).eps * max(A.shape) * max(s)

# индексы
independent_indices = np.where(s > threshold)[0]

# максимальная линейно независимая подсистема
max_independent_subsystem = A[:, independent_indices]

# векторы в виде линейной комбинации линейно независимых векторов
linear_combination_vectors = np.dot(max_independent_subsystem, np.linalg.inv(np.dot(max_independent_subsystem.T, max_independent_subsystem))).dot(max_independent_subsystem.T)

# Вывод результатов
print("Максимальная линейно независимая подсистема:\n", max_independent_subsystem)
print("Оставшиеся векторы в виде линейной комбинации линейно независимых векторов:\n", linear_combination_vectors)


Максимальная линейно независимая подсистема:
 [[ 1 -1]
 [ 2  1]
 [ 6  0]
 [-1 -2]
 [ 3  0]]
Оставшиеся векторы в виде линейной комбинации линейно независимых векторов:
 [[ 2.12121212e-01 -1.21212121e-01  1.81818182e-01  3.33333333e-01
   9.09090909e-02]
 [-1.21212121e-01  2.12121212e-01  1.81818182e-01 -3.33333333e-01
   9.09090909e-02]
 [ 1.81818182e-01  1.81818182e-01  7.27272727e-01  0.00000000e+00
   3.63636364e-01]
 [ 3.33333333e-01 -3.33333333e-01  2.08166817e-17  6.66666667e-01
   1.04083409e-17]
 [ 9.09090909e-02  9.09090909e-02  3.63636364e-01  0.00000000e+00
   1.81818182e-01]]


Задание 107


In [8]:
import numpy as np

a1 = np.array([-1,  2,  1])
a2 = np.array([ 2,  1, -2])
a3 = np.array([ 1,  1,  1])
x  = np.array([-3,  4,  5])

A = np.vstack([a1, a2, a3])

det_A = np.linalg.det(A)

if det_A != 0:
  print('Векторы а1, а2, а3 образуют базис')
  A = A.transpose()
  print(np.linalg.solve(A, x))
else:
  print('Векторы а1, а2, а3 не образуют базис')

[[-1  2  1]
 [ 2  1 -2]
 [ 1  1  1]]
Векторы а1, а2, а3 образуют базис
[ 2. -1.  1.]


Задание 122

In [9]:
import numpy as np

A = np.array([[5, 6, -3], [-1, 0, 1], [1, 2, -1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print('Собственные значения', eigenvalues, '\nСобственные векторы', eigenvectors)

Собственные значения [-0.73205081  2.73205081  2.        ] 
Собственные векторы [[ 6.13290462e-01 -9.45295908e-01 -8.94427191e-01]
 [-2.04430154e-01  3.15098636e-01  4.47213595e-01]
 [ 7.62943721e-01 -8.44304250e-02  4.40659898e-16]]


Задание 130

In [10]:
import numpy as np

A = np.array([[1, 2, 0], [0, 2, 0], [-2, -2, -1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

if np.allclose(eigenvalues, np.unique(eigenvalues)):
  print("Матрица может быть приведена к диагональной форме.")

  D = np.diag(eigenvalues)
  V_inv = np.linalg.inv(eigenvectors)
  diagonal_matrix = np.dot(np.dot(V_inv, A), eigenvectors)

  print(diagonal_matrix)
else:
  print("Матрица не может быть приведена к диагональной форме.")

Матрица может быть приведена к диагональной форме.
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  2.]]
